version: '3'

services:
  sleek-airflow:
    image: sample-airflow:latest
    
    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"
    command: airflow standalone --web-server-host 0.0.0.0
