services:
  ecomm-airflow:
    container_name: ecomm_airflow
    build:
      context: ./ecomm_airflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ecomm_airflow/dags:/opt/airflow/dags
      - ./ecomm_airflow/logs:/opt/airflow/logs
      - ./ecomm_airflow/utils:/opt/airflow/utils
      - ./ecomm_airflow/data:/opt/airflow/data
      - ./ecomm_dbt:/opt/airflow/dbt
    command:  airflow standalone